### PR TITLE
Update week-1.md

### PR DESCRIPTION
**Pull request by Yuliya-Kaleda**

### CODE REVIEW

**Comment by amyquispe** [comment]
Yuliya - Can you link me to the PR instead?

**Comment by Yuliya-Kaleda** [comment]
If you mean my repo with edits, it is here https://github.com/Yuliya-Kaleda/MemeProject

**Comment by amyquispe** [comment]
No, I mean a pull request so I can clearly see your edits.

**Comment by Yuliya-Kaleda** [comment]
I did submit the pull request to the original repo. But as i mentioned in the slack message before, I started to work on the HW before I realized we were supposed to fork the original repo. So I just cloned the original repo( without forking). As a result, later when I forked it and added the modified files, Git didn't let me push ( failed to push some refs). I was trying to fix it, but could not...no solution online.  So I just edited the files online in my repo and submitted the PR. So yoi won't see the changes as we usually see them in PR bcI deleted the whole file and added the refactored version. But all my changes are included in /\* */. Only in this way I managed to submit PR. I am sorry for any inconvenience I may have caused, that was the only way I could resolve that issue. I sent you a slack message yesterday.

**Comment by Yuliya-Kaleda** [comment]
https://github.com/MadelynTav/MemeProject/pull/23

**Comment by Yuliya-Kaleda** [comment]
My HW pull request to your repo is still open... I can see it, although I did it at 9 yesterday.

**Pull request merged**
